plugins {
    id 'java-library'
    id 'maven-publish'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = "${mod_id}-${project.name}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }
    maven {
        name = 'Illusive Soulworks'
        url = 'https://maven.theillusivec4.top/'
    }
    maven {
        name = 'Wisp Forest'
        url = 'https://maven.wispforest.io/releases'
        content { includeGroupAndSubgroups('io.wispforest') }
    }
    maven {
        name = 'Sinytra'
        url = 'https://maven.su5ed.dev/releases'
        content { includeGroupAndSubgroups('org.sinytra') }
    }
    maven {
        name = 'Fuzs'
        url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven'
        content { includeGroupAndSubgroups('fuzs') }
    }
    maven {
        name = 'CurseForge'
        url = 'https://cursemaven.com'
        content { includeGroup 'curse.maven' }
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content { includeGroup 'maven.modrinth' }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:deprecation'
}

tasks.withType(Javadoc).configureEach {
    failOnError = false
}

sourcesJar {
    from(rootProject.file('LICENSE.md')) {
        rename { "${it}_${mod_name}" }
    }
}

jar {
    from(rootProject.file('LICENSE.md')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_authors,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_authors,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'                : version,
            'group'                  : project.group,
            'minecraft_version'      : minecraft_version,
            'minecraft_version_range': minecraft_version_range,
            'fabric_version'         : fabric_version,
            'fabric_loader_version'  : fabric_loader_version,
            'fcap_version'           : fcap_version,
            'mod_id'                 : mod_id,
            'mod_name'               : mod_name,
            'mod_license'            : mod_license,
            'mod_version'            : mod_version,
            'mod_authors'            : mod_authors,
            'mod_description'        : mod_description,
            'neoforge_version'       : neoforge_version,
            'neoforge_version_range' : neoforge_version_range,
            'loader_version_range'   : loader_version_range,
            'java_version'           : java_version
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            name = 'BreakInBlocks'
            url = version.toString().endsWith('-SNAPSHOT') ?
                    'https://maven.breakinblocks.com/snapshots' :
                    'https://maven.breakinblocks.com/releases'
            credentials {
                username = System.getenv('MAVEN_USER') ?: ''
                password = System.getenv('MAVEN_TOKEN') ?: ''
            }
        }
    }
}
